export const ADD_PROJECT = "ADD_PROJECT";
export const SHOW_FORM = "SHOW_FORM";
export const HIDE_FORM = "HIDE_FORM";
export const SHOW_PROJECT_VIEW = "SHOW_PROJECT_VIEW";
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const HIDE_PROJECT_VIEW = "HIDE_PROJECT_VIEW";

export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
